export interface Product {
   modelo               : string
   slug                 : string
   coleccion            : string
   formato              : string
   m2_por_caja          : string
   superficie           : string
   material             : string
   variacion_tono       : string
   borde                : string
   ubicación            : string
   tipo_transito        : string
   junta_minima         : string
   lugar_uso            : string
   espesor              : string
   pais_origen          : string
   imagen               : string
   aplicacion           : string
   precio               : number
}

export const products: Product[] = [
   {
       "modelo": "CALACATA LIGTH PL",
       "slug": "calacata-light-pl-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/calacata_light_pl.png",
       "aplicacion": "/ambientes/calacata_light_pl.jpg",
       "precio": 130
   },
   {
       "modelo": "CALACATA LIGTH AC",
       "slug": "calacata-light-ac-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/calacata_light_ac.jpg",
       "aplicacion": "/ambientes/calacata_light_ac.jpg",
       "precio": 130
   },
   {
       "modelo": "CALACATA ORO PL",
       "slug": "calacata-oro-pl-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/calacata_oro_pl.jpg",
       "aplicacion": "/ambientes/calacata_oro_pl.jpg",
       "precio": 130
   },
   {
       "modelo": "CALACATA ORO AC",
       "slug": "calacata-oro-ac-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.19",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/calacata_oro_ac.jpg",
       "aplicacion": "/ambientes/calacata_oro_ac.jpg",
       "precio": 130
   },
   {
       "modelo": "ROMA LIGHT PL",
       "slug": "roma-light-pl-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.19",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB ",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/roma_light_pl.jpg",
       "aplicacion": "/ambientes/roma_light_pl.jpg",
       "precio": 130
   },
   {
       "modelo": "TASOS NUDE PL",
       "slug": "tasos-nude-pl-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/tasos_nude_pl.jpg",
       "aplicacion": "/ambientes/tasos_nude_pl.jpg",
       "precio": 130
   },
   {
       "modelo": "TASOS GREY PL",
       "slug": "tasos-grey-pl-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/tasos_grey_pl.jpg",
       "aplicacion": "/ambientes/tasos_grey_pl.jpg",
       "precio": 130
   },
   {
       "modelo": "SALENTO PL",
       "slug": "salento-pl-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB ",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/salento_nude_pl.jpg",
       "aplicacion": "/ambientes/salento_nude_pl.jpg",
       "precio": 130
   },
   {
       "modelo": "BELLAGIO CLASICC PL",
       "slug": "bellagio-clasicc-pl-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/bellagio_classic_pl.jpg",
       "aplicacion": "/ambientes/bellagio_classic_pl.jpg",
       "precio": 130
   },
   {
       "modelo": "ROMA GRIS PL",
       "slug": "roma-gris-pl-60-120",
       "coleccion": "PALACIO",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB ",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/roma_gris_pl.jpg",
       "aplicacion": "/ambientes/roma_gris_pl.jpg",
       "precio": 130
   },
   {
       "modelo": "MOBY PLATINA AC",
       "slug": "moby-platina-ac-60-120",
       "coleccion": "CIUDAD",
       "formato": "60 x 120",
       "m2_por_caja": "2.19",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - VARIACIÓN MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/moby_platina_ac.jpg",
       "aplicacion": "/ambientes/moby_platina_ac.jpg",
       "precio": 130
   },
   {
       "modelo": "TOWN CEMENT AC",
       "slug": "town-cement-ac-60-120",
       "coleccion": "CIUDAD",
       "formato": "60 x 120",
       "m2_por_caja": "2.19",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR ",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/town_cement_ac.jpg",
       "aplicacion": "/ambientes/town_cement_ac.jpg",
       "precio": 130
   },
   {
       "modelo": "TOWN WHITE AC",
       "slug": "town-white-ac-60-120",
       "coleccion": "CIUDAD",
       "formato": "60 x 120",
       "m2_por_caja": "2.15",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/town_white_ac.webp",
       "aplicacion": "/ambientes/town_white_ac.webp",
       "precio": 130
   },
   {
       "modelo": "MOBY PÉROLA AC",
       "slug": "moby-perola-ac-60-120",
       "coleccion": "CIUDAD",
       "formato": "60 x 120",
       "m2_por_caja": "2.19",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - VARIACIÓN MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/moby_perola_ac.jpg",
       "aplicacion": "/ambientes/moby_perola_ac.jpg",
       "precio": 130
   },
   {
       "modelo": "CALACATA LIGHT PL",
       "slug": "calacata-light-pl-120-120",
       "coleccion": "PALACIO",
       "formato": "120 x 120",
       "m2_por_caja": "2.86",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.5 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/calacata_light_pl.png",
       "aplicacion": "/ambientes/calacata_light_pl.jpg",
       "precio": 200
   },
   {
       "modelo": "CALACATA ORO PL",
       "slug": "calacata-oro-pl-120-120",
       "coleccion": "PALACIO",
       "formato": "120 x 120",
       "m2_por_caja": "2.83",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.5 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/calacata_oro_pl.jpg",
       "aplicacion": "/ambientes/calacata_oro_pl.jpg",
       "precio": 200
   },
   {
       "modelo": "TOQUIO ICE AC",
       "slug": "toquio-ice-ac-120-120",
       "coleccion": "CIUDAD",
       "formato": "120 x 120",
       "m2_por_caja": "2.86",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO ",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.5 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/toquio_ice_ac.jpg",
       "aplicacion": "/ambientes/toquio_ice_ac.jpg",
       "precio": 200
   },
   {
       "modelo": "TOQUIO GREY AC",
       "slug": "toquio-grey-ac-120-120",
       "coleccion": "CIUDAD",
       "formato": "120 x 120",
       "m2_por_caja": "2.86",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN ",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.5 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/toquio_grey_ac.jpg",
       "aplicacion": "/ambientes/toquio_grey_ac.jpg",
       "precio": 200
   },
   {
       "modelo": "EGEO GREY PL",
       "slug": "egeo-grey-pl-120-120",
       "coleccion": "PALACIO",
       "formato": "120 x 120",
       "m2_por_caja": "2.83",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V3 - MEDIA",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.5 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/egeo_grey_pl.jpg",
       "aplicacion": "/ambientes/egeo_grey_pl.jpg",
       "precio": 200
   },
   {
       "modelo": "PALATINO LIGHT AC",
       "slug": "palatino-light-ac-120-120",
       "coleccion": "PALACIO",
       "formato": "120 x 120",
       "m2_por_caja": "2.86",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN ",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.5 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/palatino_light_ac.jpg",
       "aplicacion": "/ambientes/palatino_light_ac.jpg",
       "precio": 200
   },
   {
       "modelo": "VEJA DARK GREY PL",
       "slug": "veja-dark-grey-pl-80-80",
       "coleccion": "PALACIO",
       "formato": "80 x 80",
       "m2_por_caja": "2.64",
       "superficie": "PULIDO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LB",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PARED - PISOS",
       "espesor": "9.5 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/veja_dark_grey_ac.jpg",
       "aplicacion": "/ambientes/veja_dark_grey_ac.jpg",
       "precio": 110
   },
   {
       "modelo": "NEGARA CREMA AC",
       "slug": "negara-crema-pl-20-120",
       "coleccion": "BOSQUE",
       "formato": "20 x 120",
       "m2_por_caja": "1.92",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/negara_crema_ac.jpg",
       "aplicacion": "",
       "precio": 130
   },
   {
       "modelo": "LEGNO CARVALHO AC",
       "slug": "legno-carvalho-ac-20-120",
       "coleccion": "BOSQUE",
       "formato": "20 x 120",
       "m2_por_caja": "1.92",
       "superficie": "SATINADO",
       "material": "ESMALTADO",
       "variacion_tono": "V2 - POCA VARIACIÓN",
       "borde": "RECTIFICADO",
       "ubicación": "INTERIOR",
       "tipo_transito": "LC",
       "junta_minima": "1.5 mm",
       "lugar_uso": "PISOS",
       "espesor": "9.1 mm",
       "pais_origen": "BRASIL",
       "imagen": "/pisos/legno_carvalho.jpg",
       "aplicacion": "",
       "precio": 130
   }
]